[package]
name = "chess-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.25.0"
events_emitter = "0.1.3"
intuitive = {version = "0.6.2", features = ["experimental"]}
pleco = "0.5.0"
rustneat = "0.2.1"
