[package]
name = "chess"
version = "0.1.0"
edition = "2021"

[dependencies]
atomicfloat = "0.1.0"
eframe = "0.24.1"
egui_extras = { version = "0.24.2", features = ["file", "svg"] }
itertools = "0.12.0"
rayon = "1.8.0"

[features]
gen-tables = []
