[package]
name = "chess-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.2.1", features = ["derive"] }
crossterm = "0.25.0"
intuitive = {version = "0.6.2", features = ["experimental"]}
rand = "0.8.5"
syn = "2.0.13"
